### ISSUE TITLE
board design

### ISSUE THREAD

**Issue by MaurerKrisztian** [MaurerKrisztian/TaskManager#3]
![image](https://user-images.githubusercontent.com/48491140/163676841-197c729e-9349-47ca-ad5e-fa3401dec99b.png)
https://www.figma.com/file/lMUuw19njGROdLthLvO9ej/short-task?node-id=13%3A49

Should change the task board design something like this.

Task dessign issue: https://github.com/MaurerKrisztian/TaskManager/issues/4

**Comment by Paul0908** [comment]
I would love to change the design. It would be my first issue but my strengths are angular and also CSS.

**Comment by MaurerKrisztian** [comment]
Hello, you can find the component here: /main/src/app/task-board
Basically you just need to rewrite html and css with example data and then I'll do the rest. You can delete the current css formatting.

If you haven't made a pull request yet, check it out https://opensource.com/article/19/7/create-pull-request-github but if you need help just ask.

If you have an idea for a better design feel free to include it.
Have fun! 😃

**Comment by MaurerKrisztian** [comment]
Thank you for your contribution. :tada: I really like the new design. If you like this project consider giving a star.  :star:

**Comment by MaurerKrisztian** [comment]
Remaining tasks:
- [ ] board css adjusting
