### ISSUE TITLE
Short task design

### ISSUE THREAD

**Issue by MaurerKrisztian** [MaurerKrisztian/TaskManager#4]
https://www.figma.com/file/lMUuw19njGROdLthLvO9ej/short-task?node-id=0%3A1

![image](https://user-images.githubusercontent.com/48491140/163675347-d4c85b88-c241-4c29-b636-100600be634b.png)

Should change the short task design something like this. (labels, title, worked time, attachments, remaining time to start)

**Comment by maurerlajos1** [comment]
Hey. I can do this

**Comment by MaurerKrisztian** [comment]
Looks good, thank you
